Handling embedded subProcess
Activiti/activiti-cloud-runtime-bundle-service pull request #302
Opened 2019-05-09 21:30 UTC by CTI777

Related to https://github.com/Activiti/Activiti/issues/2735

2019-05-14 16:27 UTC, erdemedeiros requested changes
Some small concerns. See my comments bellow.

2019-05-14 16:27 UTC, erdemedeiros commented on activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/AuditProducerIT.java
> +    public void testEmbeddedSubProcesses() {
@CTI777, let's create another test suite to cover embedded subprocesses (`EmbeddedSubProcessAuditIT`). This class is becoming too big.

2019-05-14 16:27 UTC, erdemedeiros commented on activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/AuditProducerIT.java
> +        List<org.activiti.engine.runtime.ProcessInstance> processes = runtimeService.createProcessInstanceQuery()
Prefer to use the API than internal `RuntimeService`: you can use `ProcessInstanceRestTemplate.getSubprocesses(processInstanceId)` for this.

2019-05-14 16:27 UTC, erdemedeiros commented on activiti-cloud-starter-runtime-bundle/src/test/resources/processes/activitySignalEventsInSubprocess.bpmn20.xml
> +	<subProcess id="eventSubProcess" name="eventSubProcess" triggeredByEvent="true">
You should remove `triggeredByEvent="true"`, as it's not triggered by an event anymore.

2019-05-14 17:03 UTC, CTI777 commented
@erdemedeiros @salaboy Another test added, subProcess with start message event
@erdemedeiros Refactoring made

2019-05-27 09:26 UTC, erdemedeiros approved these changes

2019-05-30 06:45 UTC, salaboy approved these changes

2019-05-30 07:29 UTC, merged