Integration test for events raised by parallelGateway
Activiti/activiti-cloud-runtime-bundle-service pull request #311
Opened 2019-05-22 14:40 UTC by CTI777

Related to https://github.com/Activiti/Activiti/issues/2762

2019-05-23 11:29 UTC, salaboy requested changes
@CTI777 this should include a couple of tests where the exclusive gateway is tested with conditions and variables. The idea is to check that variables are created and used inside a condition and that the gateway output is the correct one as well as all the events.

2019-05-24 08:45 UTC, CTI777 commented
@salaboy I have extended test for exclusive gateway to check conditions, events and variables

2019-06-11 13:09 UTC, salaboy approved these changes

2019-06-11 14:31 UTC, erdemedeiros approved these changes

2019-06-11 14:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Activiti/activiti-cloud-runtime-bundle-service?pullRequest=311) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Activiti/activiti-cloud-runtime-bundle-service?pullRequest=311) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: CTI777<br/>:x: mergify[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Activiti/activiti-cloud-runtime-bundle-service?pullRequest=311) it.</sub>

2019-06-11 16:13 UTC, merged