Integration test for the inclusive Gateway added
Activiti/activiti-cloud-runtime-bundle-service pull request #312
Opened 2019-05-27 19:36 UTC by CTI777

Related to https://github.com/Activiti/Activiti/issues/2739

2019-06-06 13:26 UTC, erdemedeiros requested changes
Thanks @CTI777,

See my comments related to tests. 
Also, in this test you are covering the where the inclusive gateway is used to fork the path, I think we need to cover the case where it's used to merge paths as well.

2019-06-06 13:26 UTC, erdemedeiros commented on activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/InclusiveGatewayAuditProducerIT.java
> +        checkVariable(processInstanceId, "input", 0);
@CTI777 I think that there is no need to test variable creation here. This is already tested in other tests so we can trust the variable will be created.
Also, I think you can set the initial value to `1`, so you don't need to update the variable while completing the first task and we can keep the test as simple as possible (testing only events related to the inclusive gateway and the gateway behavior).

2019-06-06 13:26 UTC, erdemedeiros commented on activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/InclusiveGatewayAuditProducerIT.java
> +        String processDefinitionKey = processInstance.getBody().getProcessDefinitionKey();
I don't think you need this variable: the process definition key will be the constant `INCLUSIVE_GATEWAY_PROCESS`

2019-06-06 13:26 UTC, erdemedeiros commented on activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/InclusiveGatewayAuditProducerIT.java
> +                                    .withVariables(Collections.singletonMap("input",3))
I don't think you need to update the variable value at this point as the execution has already passed the point where the variable is used for a decision.

2019-06-06 13:26 UTC, erdemedeiros commented on activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/InclusiveGatewayAuditProducerIT.java
> +                                    .withVariables(Collections.singletonMap("input",4))
No need to update the variable here neither.

2019-06-06 14:39 UTC, CTI777 commented
@erdemedeiros 
Refactoring for the test made

2019-06-06 19:21 UTC, salaboy approved these changes

2019-06-10 08:54 UTC, salaboy approved these changes

2019-06-10 09:08 UTC, erdemedeiros approved these changes

2019-06-10 09:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Activiti/activiti-cloud-runtime-bundle-service?pullRequest=312) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Activiti/activiti-cloud-runtime-bundle-service?pullRequest=312) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: CTI777<br/>:x: mergify[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Activiti/activiti-cloud-runtime-bundle-service?pullRequest=312) it.</sub>

2019-06-11 09:52 UTC, merged