Dev rfranchini aae 77 store extension file to db
Activiti/activiti-cloud-runtime-bundle-service pull request #404
Opened 2019-10-16 13:43 UTC by robfrank

fix code to use ProcessExtensionService instead of  Map<String, ProcessExtensionModel> processExtensionModelMap;

2019-10-17 14:07 UTC, miguelruizdev approved these changes

2019-10-17 14:25 UTC, erdemedeiros requested changes

2019-10-17 14:25 UTC, erdemedeiros commented on activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/ProcessVariablesPayloadValidator.java
> +        ProcessExtensionModel processExtensionModel = processExtensionService.getExtensionsForId(processDefinitionKey);
Here process extension service is expecting `processDefinitionId`, but you're passing `processDefinitionKey`. I think you can rename the parameter to `processDefinitionId` and make sure that all the callers are passing `id` and not `key`. For instance, https://github.com/Activiti/activiti-cloud-runtime-bundle-service/blob/develop/activiti-cloud-services-runtime-bundle/activiti-cloud-services-rest-impl/src/main/java/org/activiti/cloud/services/rest/controllers/ProcessInstanceVariableControllerImpl.java#L69

2019-10-23 08:13 UTC, miguelruizdev approved these changes

2019-10-23 08:13 UTC, miguelruizdev commented on activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/InclusiveGatewayAuditProducerIT.java
> +            processDefinitionIds.put(pd.getKey(), pd.getId());
Are we storing all the IDs available under the scope of this test class?
Is that something we'll have to do in each and every one of them?
I assume that the overhead that this adds is not a big deal, right?

2019-10-23 08:22 UTC, robfrank commented on activiti-cloud-starter-runtime-bundle/src/test/java/org/activiti/cloud/starter/tests/services/audit/InclusiveGatewayAuditProducerIT.java
> +            processDefinitionIds.put(pd.getKey(), pd.getId());
It's an IT test: overhead is very low. I just duplicated some code from test to test, I don't like it very much, but I tend to allow/tolerate  duplication in test code just for readability

2019-10-29 14:11 UTC, erdemedeiros approved these changes

2019-10-29 14:38 UTC, merged